# Generated by Django 5.1.4 on 2025-01-03 15:01

from django.db import migrations

def assign_default_artist(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Artist = apps.get_model('artworks', 'Artist')
    Artwork = apps.get_model('artworks', 'Artwork')

    # Create a default user and artist
    default_user, _ = User.objects.get_or_create(username='default_artist', email='artist@example.com')
    default_artist, _ = Artist.objects.get_or_create(user=default_user, bio='Default artist for existing artworks.')

    # Assign the default artist to all artworks
    Artwork.objects.filter(artist__isnull=True).update(artist=default_artist)

class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0003_alter_artwork_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_default_artist),
    ]

